name: Conventional Commits

on:
  pull_request:
    branches:
      - main
      - release/**

permissions:
  contents: read

jobs:
  commitsar:
    name: Validate for conventional commits
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - name: Run commitsar
        uses: docker://outillage/commitsar:0.11.2
